[package]
name = "dungeon_helper"
version = "0.1.0"
authors = ["James Hales <james@jameshales.org>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
rand = "0.7.2"
regex = "1.3.1"
serenity = "0.7.2"
